[project]
name = "yolov3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[tool.black]
line-length = 120  # 根据需要设置行长度
skip-string-normalization = true  # 防止单引号转换为双引号

[tool.ruff]
