voc:
  class_name:
    [
      "aeroplane",
      "bicycle",
      "bird",
      "boat",
      "bottle",
      "bus",
      "car",
      "cat",
      "chair",
      "cow",
      "diningtable",
      "dog",
      "horse",
      "motorbike",
      "person",
      "pottedplant",
      "sheep",
      "sofa",
      "train",
      "tvmonitor",
    ]
coco:
  class_name:
    [
      "airplane",
      "apple",
      "backpack",
      "banana",
      "baseball bat",
      "baseball glove",
      "bear",
      "bed",
      "bench",
      "bicycle",
      "bird",
      "boat",
      "book",
      "bottle",
      "bowl",
      "broccoli",
      "bus",
      "cake",
      "car",
      "carrot",
      "cat",
      "cell phone",
      "chair",
      "clock",
      "couch",
      "cow",
      "cup",
      "dining table",
      "dog",
      "donut",
      "elephant",
      "fire hydrant",
      "fork",
      "frisbee",
      "giraffe",
      "hair drier",
      "handbag",
      "horse",
      "hot dog",
      "keyboard",
      "kite",
      "knife",
      "laptop",
      "microwave",
      "motorcycle",
      "mouse",
      "orange",
      "oven",
      "parking meter",
      "person",
      "pizza",
      "potted plant",
      "refrigerator",
      "remote",
      "sandwich",
      "scissors",
      "sheep",
      "sink",
      "skateboard",
      "skis",
      "snowboard",
      "spoon",
      "sports ball",
      "stop sign",
      "suitcase",
      "surfboard",
      "teddy bear",
      "tennis racket",
      "tie",
      "toaster",
      "toilet",
      "toothbrush",
      "traffic light",
      "train",
      "truck",
      "tv",
      "umbrella",
      "vase",
      "wine glass",
      "zebra",
    ]
