hardware:
  device: 'cpu' # 优先使用 GPU，否则使用 CPU
training:
  batch_size: 16 # 批大小
  train_path: 'coco_train.txt'
  val_path: 'coco_val.txt'
model:
  anchors: # Anchor boxes for YOLO detection
    - [7, 9]
    - [16, 24]
    - [43, 26]
    - [29, 60]
    - [72, 56]
    - [63, 133]
    - [142, 96]
    - [166, 223]
    - [400, 342]
  anchors_mask: # Anchor mask for different scales
    - [6, 7, 8] # 大尺度
    - [3, 4, 5] # 中尺度
    - [0, 1, 2] # 小尺度
  stride: [32, 16, 8] # 特征图下采样步幅
dataset:
  length: 80
  class_names:
    [
      'airplane',
      'apple',
      'backpack',
      'banana',
      'baseball bat',
      'baseball glove',
      'bear',
      'bed',
      'bench',
      'bicycle',
      'bird',
      'boat',
      'book',
      'bottle',
      'bowl',
      'broccoli',
      'bus',
      'cake',
      'car',
      'carrot',
      'cat',
      'cell phone',
      'chair',
      'clock',
      'couch',
      'cow',
      'cup',
      'dining table',
      'dog',
      'donut',
      'elephant',
      'fire hydrant',
      'fork',
      'frisbee',
      'giraffe',
      'hair drier',
      'handbag',
      'horse',
      'hot dog',
      'keyboard',
      'kite',
      'knife',
      'laptop',
      'microwave',
      'motorcycle',
      'mouse',
      'orange',
      'oven',
      'parking meter',
      'person',
      'pizza',
      'potted plant',
      'refrigerator',
      'remote',
      'sandwich',
      'scissors',
      'sheep',
      'sink',
      'skateboard',
      'skis',
      'snowboard',
      'spoon',
      'sports ball',
      'stop sign',
      'suitcase',
      'surfboard',
      'teddy bear',
      'tennis racket',
      'tie',
      'toaster',
      'toilet',
      'toothbrush',
      'traffic light',
      'train',
      'truck',
      'tv',
      'umbrella',
      'vase',
      'wine glass',
      'zebra',
    ]
